apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: {{ .Release.Name }}-wordpress 
  namespace: {{ .Release.Namespace }} 
  annotations: 
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure 
spec: 
  ingressClassName: {{ .Values.ingress.className }} 
  tls: 
    - hosts: 
        - {{ .Values.ingress.host }} 
      secretName: {{ .Values.ingress.secretName }} 
  rules: 
    - host: {{ .Values.ingress.host }} 
      http: 
        paths: 
          - path: / 
            pathType: Prefix 
            backend: 
              service: 
                name: {{ .Release.Name }}-wordpress 
                port: 
                  number: {{ .Values.service.port }} 
{{- end }} 
