apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-wordpress 
  namespace: {{ .Release.Namespace }} 
  labels: 
    app: wordpress 
spec: 
  type: {{ .Values.service.type }} 
  selector: 
    app: wordpress 
  ports: 
    - name: http 
      port: {{ .Values.service.port }} 
      targetPort: 80 
      protocol: TCP 
