apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: database

spec:
  schedule: "0 */6 * * *"

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          containers:
            - name: postgres-backup
              image: postgres:16

              env:
                - name: PGHOST
                  value: postgres

                - name: PGPORT
                  value: "5432"

                - name: PGDATABASE
                  value: postgres

                - name: PGUSER
                  value: postgres_admin

                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: POSTGRES_PASSWORD

              command:
                - pg_dump
                - -Fc
                - -f
                - /backups/postgres_backup.dump
                - postgres

              volumeMounts:
                - name: backup-storage
                  mountPath: /backups

          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-backups
